spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/WeatherDiary
    driver-class-name: org.mariadb.jdbc.Driver
    username: user1
    password: a1234
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

openWeather:
  apikey: 1ac079210d14995f9a359084a2ed2b93
  url: https://api.openweathermap.org/data/2.5/weather?q=seoul&appid=

logging:
  config: classpath:logback-spring.xml
